FROM node:20 as builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

FROM node:20

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json .
COPY --from=builder /app/prisma ./prisma 

RUN npm ci --only=production  # Install production deps

ENV DATABASE_URL="mysql://dev_user:mysql_pwd@db:2100/db"

EXPOSE $PORT

CMD ["npm", "run", "host"]