FROM node:20

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

ENV DATABASE_URL="mysql://dev_user:mysql_pwd@db:2100/db"

RUN npx prisma generate

EXPOSE $PORT

CMD ["npm", "run", "host"]